#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Get gruvbox colors if they exist

if [ -f ~/.vim/bundle/gruvbox/gruvbox_256palette.sh ]
then
  source ~/.vim/bundle/gruvbox/gruvbox_256palette.sh
fi

# Source env vars in .zvars directory

if [ -d ~/.zvars ]
then
  source ~/.zvars/*.zsh
fi

# Source .zsh files in .zaliases directory

if [ -d ~/.zaliases ]
then
  source ~/.zaliases/*.zsh
fi

# Source .zsh files in .zfuncs directory

if [ -d ~/.zfuncs ]
then
  source ~/.zfuncs/*.zsh
fi

